<?php
namespace config;

define('RESIEXCHANGE_QUESTIONS_DAILY_MAX', 100);
define('RESIEXCHANGE_ANSWERS_DAILY_MAX', 100);
define('RESIEXCHANGE_COMMENTS_DAILY_MAX', 100);

define('RESIEXCHANGE_QUESTION_VOTEUP_DAILY_MAX', 50);
define('RESIEXCHANGE_ANSWER_VOTEUP_DAILY_MAX', 50);
define('RESIEXCHANGE_COMMENT_VOTEUP_DAILY_MAX', 50);

define('RESIEXCHANGE_QUESTION_VOTEDOWN_DAILY_MAX', 50);
define('RESIEXCHANGE_ANSWER_VOTEDOWN_DAILY_MAX', 50);
define('RESIEXCHANGE_COMMENT_VOTEDOWN_DAILY_MAX', 50);

define('RESIEXCHANGE_QUESTION_FLAG_DAILY_MAX', 50);
define('RESIEXCHANGE_ANSWER_FLAG_DAILY_MAX', 50);
define('RESIEXCHANGE_COMMENT_FLAG_DAILY_MAX', 50);